=head1 NAME

Contentment::Manual - Table of Contents 

=head1 TABLE OF CONTENTS

=head2 MANUAL

L<Contentment::Manual::Install> - Installation instructions

=head2 CORE API DOCUMENTATION

Plan on reading this if you want to do any development with Contentment.

L<Contentment> - Contentment is a Perl-based web content management system.

L<Contentment::FileType> - Contract all filetype plugins must adhere to

L<Contentment::Hooks> - Runs the Contentment hook system

L<Contentment::Log> - Handles logging for Contentment

L<Contentment::Request> - Class responsible for managing incoming requests

L<Contentment::Response> - Handles Contentment response handling

=head1 PLUGIN DOCUMENTATION

TODO I need to put together links to documentation for each plugin.

=head1 COPYRIGHT

Copyright 2005 Andrew Sterling Hanenkamp. All Rights Reserved.

=for meta short_title => 'Manual'
